### ISSUE TITLE
Calendar popup issues

### ISSUE THREAD

**Issue by 9teen90nine** [taskany-inc/hire#115]
Currently the form is wrong width and the dropdown doesn't look like one - that affects ALL dropdowns

![Image](https://github.com/taskany-inc/hire/assets/3691805/d21315b5-b373-4ad3-ad71-f77e6cf8fdc5)

**Comment by Katrin-kudryash** [comment]
![Image](https://github.com/taskany-inc/hire/assets/81121562/aeacf8ed-6cbe-4a5b-b73f-68d635b1df54)
