### ISSUE TITLE
Locale as in system

### ISSUE THREAD

**Issue by nyet-ty** [taskany-inc/hire#224]

**Comment by tsumo** [comment]
@nyet-ty @9teen90nine
 Let's write out explicit redirects for each case

  | /problems | /ru/problems | /en/problems
-- | -- | -- | --
Accept-Language: en-EN |   |   |  
Accept-Language: ru-RU |   |   |  
Accept-Language: * |   |   |

**Comment by 9teen90nine** [comment]
Ok:

 | /problems | /ru/problems | /en/problems
-- | -- | -- | --
Accept-Language: en-EN | /problems  | /problems  |  
Accept-Language: ru-RU | /ru/problems | /ru/problems  |  
Accept-Language: * | /ru/problems  | /problems  |
