### ISSUE TITLE
Grade buttons are not visible in light theme

### ISSUE THREAD

**Issue by nyet-ty** [taskany-inc/hire#339]
![Image](https://github.com/taskany-inc/hire/assets/61706821/2348ee17-9dc9-4226-ab61-eb00e33f252e)

dark theme for for comparison

![Image](https://github.com/taskany-inc/hire/assets/61706821/e0c80ea8-1468-426b-bd19-e131b0ddbaa9)

**Comment by tsumo** [comment]
Same thing with hire buttons and light-colored tags

**Comment by nyet-ty** [comment]
![Image](https://github.com/taskany-inc/hire/assets/61706821/e13594db-405d-4ae8-8b90-7ca78580be18)

**Comment by nyet-ty** [comment]
Colors for text and border of GradeButtons and tags should be from @taskany/colors
