### ISSUE TITLE
Parse a CV to create/update a candidate and an interview

### ISSUE THREAD

**Issue by 9teen90nine** [taskany-inc/hire#414]
1. Get text from pdf file
2. Sent to processer to find matches and contacts

**Comment by tsumo** [comment]
[resume-parser](https://www.npmjs.com/package/resume-parser), [simple-resume-parser](https://www.npmjs.com/package/simple-resume-parser), [resume-parser-extended](https://www.npmjs.com/package/resume-parser-extended): parses only emails, sometimes profile links.

[open-resume](https://www.open-resume.com/resume-parser): email, phone, sometimes links

**Comment by tsumo** [comment]
https://www.recruitment-copilot.com/resume-parser: works perfectly, commercial :(

**Comment by tsumo** [comment]
https://github.com/OmkarPathak/pyresparser: couldn't get it to work, mess of python dependencies

**Comment by tsumo** [comment]
https://github.com/kbrajwani/resume_parser: email, phone, skills
