### ISSUE TITLE
Buttons on SectionFeedback

### ISSUE THREAD

**Issue by nyet-ty** [taskany-inc/hire#643]
Locate buttons better: 
Then feedback is filled and in edit mode

**Comment by 9teen90nine** [comment]
1. Change width  of all inputs to one size. The preview button should match the container

![Image](https://github.com/taskany-inc/hire/assets/3691805/aa0ae813-cad6-409b-9cb6-a86cf33cd537)

2. Hide 'add problem' button when feedback is already submitted
3. Move 'Cancel' button in row when editing feedback (and keep add problem button there)


![Image](https://github.com/taskany-inc/hire/assets/3691805/d68689f1-c0ac-4e07-a9fc-f7f4e692dcb4)
