### ISSUE TITLE
Can't add section types to my own hiring streams

### ISSUE THREAD

**Issue by 9teen90nine** [taskany-inc/hire#97]
Looks like I don't have ownership of a new hiring stream

![Image](https://github.com/taskany-inc/hire/assets/3691805/1b70d1be-ab65-47cf-839e-776cdec5dab5)

**Comment by tsumo** [comment]
This bug occurs only with the debug auth cookie. Hire stream creator is already added to the stream managers

https://github.com/taskany-inc/hire/blob/main/src/backend/modules/hire-streams/hire-stream-db-service.ts#L49
